title: Michele Usuelli
description: Data science blog
theme: jekyll-theme-slate
gems: [jekyll-mermaid]
relative_links:
  enabled:     true
  collections: false
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  # parse markdown inside block-level HTML tag
  parse_block_html: true
